info:
  name: 用户中心
  contact: 动脑学院VIP

server:
  port: 9004
spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.193.158:3306/uaa-db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc@123
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          # 自动创建表
          auto: update
    